#pragma config(Motor,  port2,           L1,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           L2,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           R1,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           R2,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           Flip_it1,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Flip_it2,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           Twist_it,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           Pull_it,       tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int joystickTolerance = 15;
int fixNum(int num){
	if (num >= -joystickTolerance && num <= joystickTolerance)
		return 0;
	return num;
}
task main()
{
	while(1==1)
	{
		motor[R1] = motor[R2] = fixNum(vexRT[Ch2]);
		motor[L1] = motor[L2] = fixNum(vexRT[Ch3]);

		//Main arm//
		if(vexRT[Btn6U])
		{
			motor(Flip_it1) = 75;
			motor(Flip_it2) = 75;
		}
		else if(vexRT[Btn6D])
		{
			motor(Flip_it1) = -75;
			motor(Flip_it2) = -75;
		}
		else
		{
			motor(Flip_it1) = 0;
			motor(Flip_it2) = 0;
		}

		//Claw on X axis//
		if(vexRT[Btn8R])
		{
			motor(Twist_it) = 100;
		}
		else if(vexRT[Btn8L])
		{
			motor(Twist_it) = -100;
		}
		else
		{
			motor(Twist_it) = 0;
		}

		//Claw comand on Y axis//
		if(vexRT[Btn5U] == 1)
		{
			motor(Pull_it) = 100;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor(Pull_it) = -100;
		}
		else
		{
			motor(Pull_it) = 0;
		}
		//Auto code//
		if(vexRT[Btn7L])
		{
			motor[R1] = motor[R2] = motor[L1] = motor[L2] = -100;
			wait10Msec(150);
			motor[R1] = motor[R2] = motor[L1] = motor[L2] = 100;
			wait10Msec(200);
			motor[R1] = motor[R2] = motor[L1] = motor[L2] = 0;
			wait10Msec(100);
			motor[L1] = motor[L2] = -100;
			motor[R1] = motor[R2] = 100;
			wait10Msec(50);
			motor[R1] = motor[R2] = motor[L1] = motor[L2] = 0;
			wait10Msec(100);
			motor[R1] = motor[R2] = motor[L1] = motor[L2] = 100;
			wait10Msec(150);
			motor[R1] = motor[R2] = motor[L1] = motor[L2] = 0;


		}
	}
}
