#pragma config(Motor,  port2,           L1,            tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           L2,            tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           L3,            tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           R1,            tmotorVex393TurboSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           R2,            tmotorVex393TurboSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port7,           R3,            tmotorVex393TurboSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port8,           XT3,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BCD2,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Speed = 2.25;
int joystickTolerance = 15; //25; //Might be moved up to 20 to match the boost.
int fixNum(int num)
{
	if (num >= -joystickTolerance && num <= joystickTolerance)
		return 0;
	return num;
}

task main()
{

	while(true)// Test the reamp to find debug logs.
	{
		motor[L1] = motor[L2] = motor[L3] = Speed*fixNum(vexRT[Ch3]);
		motor[R1] = motor[R2] = motor[R3] = Speed*fixNum(vexRT[Ch2]);

		if(vexRT[Btn7L] == 1)
		{
			motor[L1] = motor[L2] = motor[L3] = 127;
			motor[R1] = motor[R2] = motor[R3] = -127;
		}

		else if(vexRT[Btn7R] == 1)
		{
			motor[L1] = motor[L2] = motor[L3] = -127;
			motor[R1] = motor[R2] = motor[R3] = 127;
		}

		else
		{
			motor[L1] = motor[L2] = motor[L3] = motor[R1] = motor[R2] = motor[R3] = 0;
		}
	}
}



//50
