#pragma config(Sensor, dgtl1,  the_thing,      sensorTouch)
#pragma config(Sensor, dgtl2,  yes,            sensorTouch)
#pragma config(Motor,  port2,           MotorRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           MotorLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Upything,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Upything2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Skizer2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           SpinnyDeal,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LiftyThing,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Claw,          tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int joystickTolerance = 25;
int fixNum(int num){
	if (num >= -joystickTolerance && num <= joystickTolerance)
		return 0;
	return num;
}
task main()
{
	while(1==1)
	{
		motor[MotorLeft] = fixNum(vexRT[Ch3]);
		motor[MotorRight] = fixNum(vexRT[Ch2]);
		//Turn table.
		if(vexRT[Btn7L] == 1) //8 Left
		{
			motor[SpinnyDeal] = 50;
		}
		else if(vexRT[Btn7R] == 1) //8 Right
		{
			motor[SpinnyDeal] = -50;
		}
		else //No input
		{
			motor[SpinnyDeal] = 0;
		}

		//Claw code.
		if(vexRT[Btn8U] == 1) //8 Up
		{
			motor[Claw] = 80;
		}
		else if(vexRT[Btn8D] == 1) //8 Down
		{
			motor[Claw] = -80;
		}
		else //No input
		{
			motor[Claw] = 0;
		}

		//Claw lift.

		if(vexRT[Btn7U] == 1) //7 Up
		{
			motor[LiftyThing] = 100;
		}

		else if(vexRT[Btn7D] == 1) //7 Down
		{
			motor[LiftyThing] = -100;
		}
		else //No input
		{
			motor[LiftyThing] = 10;
		}


		//The the moble cone mover.
		if(vexRT[Btn6U] == 1) //6 Up
		{
			if(SensorValue[the_thing] == 0)
			{
				motor(Upything) = 90;
			}
			else
			{
				motor(Upything) = 0;
			}

			if(SensorValue[yes] == 0)//stuff
			{
				motor(Upything2) = 100;
			}
			else
			{
				motor(Upything2) = 0;
			}

		}
		else if(vexRT[Btn6D] == 1) //6 Down
		{
			motor[Upything] = -90;
			motor[Upything2] = -100;
		}
		else //No input
		{
			motor[Upything] = motor[Upything2] = 0;
		}

		//Auto task
		if(vexRT[Btn5U] == 1) //5 Up
		{									//Then hit
			if(vexRT[Btn5D] == 1) //5 Down
			{
				motor[MotorRight] = 120;
				motor[MotorLeft] = 120;
				motor[LiftyThing] = 100;
				wait(1.7);
				motor[LiftyThing] = 10;
				wait(3);//5
				//Pick it up
				motor[MotorLeft] = motor[MotorRight] = 0;
				motor[Upything] = motor[Upything2] = 100;
				motor[Claw] = -100;
				wait(2.3);//4
				//Pull it back
				motor[Claw] = 0;
				motor[Upything] = motor[Upything2] = 0;
				motor[MotorLeft] = -120;
				motor[MotorRight] = -120;
				wait(4.7);//5
				//Drop it while turning
				motor[Upything] = motor[Upything2] = -100;
				motor[MotorLeft] = 0;
				wait(2.5); //4
				//Pull back
				motor[Upything] = motor[Upything2] = 0;
				wait(0.5);
				motor[MotorLeft] = motor[MotorRight] = -100;
				wait(0.3);
				motor[MotorLeft] = motor[MotorRight] = motor [Claw] = motor[LiftyThing] = 0;
				//Wait further instructions
			}
		}
	}
}
